"""empty message

Revision ID: 536499733466
Revises: 5b662a8855ce
Create Date: 2022-11-10 12:31:06.232889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536499733466'
down_revision = '5b662a8855ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    # ### end Alembic commands ###
